# Generated by Django 4.2.1 on 2025-04-29 13:31

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
        ('women', '0007_tagpost_alter_women_managers_alter_women_cat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='women',
            name='tags_taggle',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
