# Generated by Django 4.2.1 on 2025-05-02 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0009_husband_women_husband'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='women',
            options={'get_latest_by': ['time_create'], 'ordering': ['-time_create']},
        ),
        migrations.AddField(
            model_name='husband',
            name='m_count',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
