# Generated by Django 4.2.1 on 2025-05-11 20:04

import django.core.validators
from django.db import migrations, models
import women.validators


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0011_alter_category_options_alter_women_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads_model')),
            ],
        ),
        migrations.AlterModelOptions(
            name='husband',
            options={'verbose_name': 'Мужчина', 'verbose_name_plural': 'Мужчины'},
        ),
        migrations.AlterModelOptions(
            name='tagpost',
            options={'verbose_name': 'Тег', 'verbose_name_plural': 'Теги'},
        ),
        migrations.AlterField(
            model_name='husband',
            name='age',
            field=models.IntegerField(null=True, verbose_name='Возраст'),
        ),
        migrations.AlterField(
            model_name='husband',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Имя мужчины'),
        ),
        migrations.AlterField(
            model_name='women',
            name='slug',
            field=models.SlugField(max_length=255, unique=True, validators=[django.core.validators.MinLengthValidator(5, message='Минимум 5 символов')], verbose_name='Слаг'),
        ),
        migrations.AlterField(
            model_name='women',
            name='title',
            field=models.CharField(max_length=255, validators=[django.core.validators.MinLengthValidator(5, message='Слишком короткий заголовок'), women.validators.RussianValidator()], verbose_name='Заголовок'),
        ),
    ]
