# Generated by Django 4.2.1 on 2025-05-11 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0012_uploadfiles_alter_husband_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='women',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photos/%Y/%m/%d/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='uploadfiles',
            name='file',
            field=models.FileField(upload_to='uploads_model', verbose_name='Загрузить изображение'),
        ),
    ]
