# Generated by Django 4.2.1 on 2025-05-11 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0013_women_photo_alter_uploadfiles_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uploadfiles',
            old_name='file',
            new_name='image',
        ),
    ]
